# Generated by Django 3.2.8 on 2021-11-11 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='prod_evaluation',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='product_evaluation',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('great', 'Great'), ('excellent', 'Excellent')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
